# Generated by Django 3.2.15 on 2023-09-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voites',
            new_name='votes',
        ),
    ]
